### ISSUE TITLE
[Quais] - Integrate with Core endpoint for estimated gas and estimated base fee

### ISSUE THREAD

**Issue by mibuono** [dominant-strategies/quais-6.js#21]
Integrate with the Core endpoint for reading the estimated gas and estimated base fee.

Need the get the base fee in the unit that you're interested in.  Base fee should be overloaded to return one or the other.

**Comment by rileystephens28** [comment]
**Estimate Gas**
The current version of go-quai-libp2p overloads the `quai_estimateGas` rpc method, therefore there is no additional work to do for quais.

**Base Fee**
The current version of go-quai-libp2p overloads the `quai_baseFee` rpc method, however, the Qi implementation is incomplete. 
In quais, the base fee is currently calculated based on the base fee from the previous block, this needs to change to call the available `quai_baseFee` rpc method. This will require adding `getBaseFee` to the methods switch case in 

Must modify the `AbstractProvider.getFeeData` method to accept a `txType` (0/1 or boolean type can be used) input param that will be passed along to the `quai_baseFee` rpc call. The `txType` param will determine whether the base fee is returned in units of quai (Wei or whatever the quai equivalent is) or qi (Qit)

**Comment by rileystephens28** [comment]
This will be in review until we get the QIP 2 implementation merged
