### ISSUE TITLE
[Quais] - Create method for current Qi:Quai conversion rate

### ISSUE THREAD

**Issue by mibuono** [dominant-strategies/quais-6.js#22]
Requirements:

Based on the method here: https://github.com/dominant-strategies/go-quai/issues/1394 - integrate with that method so Blockscout can consume that information via the SDK.

**Comment by rileystephens28** [comment]
```typescript
AbstractProvider.getLatestQuaiQiConversionRate(): BigInt
```
This new abstract provider method returns the qi:quai conversion rate at the latest block height (number). This function will call `AbstractProvider.getQuaiQiConversionRate` with `blockNumber` param equal to the latest block number.
