### ISSUE TITLE
[Quais] - Create method for historical Qi:Quai Method from Core

### ISSUE THREAD

**Issue by mibuono** [dominant-strategies/quais-6.js#23]
There will be a historical data method for Qi and Quai in Core that Quais needs to serve requesters.

The method, data types, and payload should be reviewed from this issue: https://github.com/dominant-strategies/go-quai/issues/1403

**Comment by rileystephens28** [comment]
This will require adding `getQuaiQiConversionRate` to the methods switch case in `JsonRpcApiProvider.getRpcRequest()`.

`AbstractProvider.getQuaiQiConversionRate(blockNumber: number): Promise<bigint>`
This new abstract provider method returns the qi:quai conversion rate at a specified block height (number). This will execute the `#perform` function with method param `getQuaiQiConversionRate`
